name: Python Linter
on: 
  push:
    branches: 
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps: 
    - uses: actions/checkout@v4
   # - run: pip install -r requirements.txt
  ruff_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruff check
        uses: astral-sh/ruff-action@v1
